2025-05-31 17:15:53,966 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:15:56,760 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:15:57,191 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:15:57,232 - etl_pipeline - ERROR - Error en ETL: module 'utils.logger' has no attribute 'error'
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\staging\staging_dim_cliente.py", line 27, in run_staging
    df.to_sql('stg_dim_cliente', session.connection(), if_exists='replace', index=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\core\generic.py", line 3087, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2008, in to_sql
    table = self.prep_table(
        frame=frame,
    ...<5 lines>...
        dtype=dtype,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1912, in prep_table
    table.create()
    ~~~~~~~~~~~~^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 988, in create
    self.pd_sql.drop_table(self.name, self.schema)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2059, in drop_table
    self.meta.reflect(
    ~~~~~~~~~~~~~~~~~^
        bind=self.con, only=[table_name], schema=schema, views=True
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\sql\schema.py", line 5873, in reflect
    raise exc.InvalidRequestError(
    ...<2 lines>...
    )
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(postgresql://postgres:***@localhost:5432/mensajeria_colombia_dw): (stg_dim_cliente)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\pipelines\etl_base.py", line 34, in run_etl_with_staging
    if not staging_fn(df_raw, session):
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\staging\staging_dim_cliente.py", line 32, in run_staging
    logger.error("Error creando tabla stg_dim_cliente", exc_info=True)
    ^^^^^^^^^^^^
AttributeError: module 'utils.logger' has no attribute 'error'
2025-05-31 17:15:57,290 - etl_pipeline - INFO - ERROR DIM_CLIENTE
2025-05-31 17:15:57,290 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:15:57,290 - etl_pipeline - INFO -   - DIM_CLIENTE    : FALLÓ
2025-05-31 17:15:57,290 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 17:19:24,035 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:19:24,619 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:19:24,687 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:19:24,727 - etl_pipeline - ERROR - Error en ETL: module 'utils.logger' has no attribute 'error'
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\staging\staging_dim_cliente.py", line 27, in run_staging
    df.to_sql('stg_dim_cliente', session.connection(), if_exists='replace', index=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\core\generic.py", line 3087, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2008, in to_sql
    table = self.prep_table(
        frame=frame,
    ...<5 lines>...
        dtype=dtype,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1912, in prep_table
    table.create()
    ~~~~~~~~~~~~^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 988, in create
    self.pd_sql.drop_table(self.name, self.schema)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2059, in drop_table
    self.meta.reflect(
    ~~~~~~~~~~~~~~~~~^
        bind=self.con, only=[table_name], schema=schema, views=True
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\sql\schema.py", line 5873, in reflect
    raise exc.InvalidRequestError(
    ...<2 lines>...
    )
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(postgresql://postgres:***@localhost:5432/mensajeria_colombia_dw): (stg_dim_cliente)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\pipelines\etl_base.py", line 34, in run_etl_with_staging
    if not staging_fn(df_raw, session):
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\staging\staging_dim_cliente.py", line 32, in run_staging
    logger.error("Error creando tabla stg_dim_cliente", exc_info=True)
    ^^^^^^^^^^^^
AttributeError: module 'utils.logger' has no attribute 'error'
2025-05-31 17:19:24,731 - etl_pipeline - INFO - ERROR DIM_CLIENTE
2025-05-31 17:19:24,732 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:19:24,732 - etl_pipeline - INFO -   - DIM_CLIENTE    : FALLÓ
2025-05-31 17:19:24,732 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 17:20:54,229 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:20:54,772 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:20:54,840 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:20:54,881 - etl_pipeline - ERROR - Error en ETL: module 'utils.logger' has no attribute 'error'
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\staging\staging_dim_cliente.py", line 27, in run_staging
    df.to_sql('stg_dim_cliente', session.connection(), if_exists='replace', index=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\core\generic.py", line 3087, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2008, in to_sql
    table = self.prep_table(
        frame=frame,
    ...<5 lines>...
        dtype=dtype,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1912, in prep_table
    table.create()
    ~~~~~~~~~~~~^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 988, in create
    self.pd_sql.drop_table(self.name, self.schema)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2059, in drop_table
    self.meta.reflect(
    ~~~~~~~~~~~~~~~~~^
        bind=self.con, only=[table_name], schema=schema, views=True
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\sql\schema.py", line 5873, in reflect
    raise exc.InvalidRequestError(
    ...<2 lines>...
    )
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(postgresql://postgres:***@localhost:5432/mensajeria_colombia_dw): (stg_dim_cliente)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\pipelines\etl_base.py", line 34, in run_etl_with_staging
    if not staging_fn(df_raw, session):
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\staging\staging_dim_cliente.py", line 32, in run_staging
    logger.error("Error creando tabla stg_dim_cliente", exc_info=True)
    ^^^^^^^^^^^^
AttributeError: module 'utils.logger' has no attribute 'error'
2025-05-31 17:20:54,886 - etl_pipeline - INFO - ERROR DIM_CLIENTE
2025-05-31 17:20:54,886 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:20:54,886 - etl_pipeline - INFO -   - DIM_CLIENTE    : FALLÓ
2025-05-31 17:20:54,886 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 17:23:31,359 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:23:31,939 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:23:32,012 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:23:32,050 - etl_pipeline - ERROR - Error en ETL: module 'utils.logger' has no attribute 'error'
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\staging\staging_dim_cliente.py", line 27, in run_staging
    df.to_sql('stg_dim_cliente', session.connection(), if_exists='replace', index=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\core\generic.py", line 3087, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2008, in to_sql
    table = self.prep_table(
        frame=frame,
    ...<5 lines>...
        dtype=dtype,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1912, in prep_table
    table.create()
    ~~~~~~~~~~~~^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 988, in create
    self.pd_sql.drop_table(self.name, self.schema)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2059, in drop_table
    self.meta.reflect(
    ~~~~~~~~~~~~~~~~~^
        bind=self.con, only=[table_name], schema=schema, views=True
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\sql\schema.py", line 5873, in reflect
    raise exc.InvalidRequestError(
    ...<2 lines>...
    )
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(postgresql://postgres:***@localhost:5432/mensajeria_colombia_dw): (stg_dim_cliente)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\pipelines\etl_base.py", line 34, in run_etl_with_staging
    if not staging_fn(df_raw, session):
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\staging\staging_dim_cliente.py", line 32, in run_staging
    logger.error("Error creando tabla stg_dim_cliente", exc_info=True)
    ^^^^^^^^^^^^
AttributeError: module 'utils.logger' has no attribute 'error'
2025-05-31 17:23:32,055 - etl_pipeline - INFO - ERROR DIM_CLIENTE
2025-05-31 17:23:32,055 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:23:32,055 - etl_pipeline - INFO -   - DIM_CLIENTE    : FALLÓ
2025-05-31 17:23:32,055 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 17:26:44,521 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:26:45,098 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:26:45,169 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:26:45,209 - etl_pipeline - INFO - ERROR DIM_CLIENTE
2025-05-31 17:26:45,209 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:26:45,210 - etl_pipeline - INFO -   - DIM_CLIENTE    : FALLÓ
2025-05-31 17:26:45,210 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 17:31:26,137 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:31:26,707 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:31:26,782 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:31:26,831 - etl_pipeline - INFO - ERROR DIM_CLIENTE
2025-05-31 17:31:26,831 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:31:26,831 - etl_pipeline - INFO -   - DIM_CLIENTE    : FALLÓ
2025-05-31 17:31:26,831 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 17:31:41,558 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:31:42,048 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:31:42,116 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:31:42,154 - etl_pipeline - INFO - ERROR DIM_CLIENTE
2025-05-31 17:31:42,154 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:31:42,154 - etl_pipeline - INFO -   - DIM_CLIENTE    : FALLÓ
2025-05-31 17:31:42,154 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 17:34:33 - etl_pipeline - DEBUG - Mensaje DEBUG - Solo visible en archivo
2025-05-31 17:34:33 - etl_pipeline - INFO - Mensaje INFO - Visible en consola y archivo
2025-05-31 17:34:33 - etl_pipeline - WARNING - Mensaje WARNING - Visible en consola y archivo
2025-05-31 17:34:33 - etl_pipeline - ERROR - Mensaje ERROR - Visible en consola y archivo
2025-05-31 17:34:33 - etl_pipeline - ERROR - Error con traceback
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\test.py", line 9, in test_logger
    1/0
    ~^~
ZeroDivisionError: division by zero
2025-05-31 17:34:50 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:34:51 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:34:51 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:34:51 - etl_pipeline - INFO - ERROR DIM_CLIENTE
2025-05-31 17:34:51 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:34:51 - etl_pipeline - INFO -   - DIM_CLIENTE    : FALLÓ
2025-05-31 17:34:51 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 17:36:01 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:36:01 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:36:01 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:36:01 - etl_pipeline - INFO - ERROR DIM_CLIENTE
2025-05-31 17:36:01 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:36:01 - etl_pipeline - INFO -   - DIM_CLIENTE    : FALLÓ
2025-05-31 17:36:01 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 17:36:20 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:36:20 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:36:20 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:36:20 - etl_pipeline - ERROR - Error en ETL: module 'utils.logger' has no attribute 'error'
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\staging\staging_dim_cliente.py", line 42, in run_staging
    logger.info(f"Staging completado ({len(df)} filas)")
    ^^^^^^^^^^^
AttributeError: module 'utils.logger' has no attribute 'info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\pipelines\etl_base.py", line 34, in run_etl_with_staging
    if not staging_fn(df_raw, session):
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\staging\staging_dim_cliente.py", line 46, in run_staging
    logger.error("Error creando tabla stg_dim_cliente", exc_info=True)
    ^^^^^^^^^^^^
AttributeError: module 'utils.logger' has no attribute 'error'
2025-05-31 17:36:20 - etl_pipeline - INFO - ERROR DIM_CLIENTE
2025-05-31 17:36:20 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:36:20 - etl_pipeline - INFO -   - DIM_CLIENTE    : FALLÓ
2025-05-31 17:36:20 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 17:37:07 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:37:08 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:37:08 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:37:08 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 17:37:08 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 17:37:08 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 17:37:08 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 17:37:08 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 17:37:08 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 17:37:08 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 17:37:08 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:37:08 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 17:37:08 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 17:38:19 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:38:19 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:38:20 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:38:20 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 17:38:20 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 17:38:20 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 17:38:20 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 17:38:20 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 17:38:20 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 17:38:20 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 17:38:20 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:38:20 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 17:38:20 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 17:45:19,650 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:45:20,217 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:45:20,289 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:45:20,332 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 17:45:20,332 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 17:45:20,334 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 17:45:20,334 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 17:45:20,341 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 17:45:20,341 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 17:45:20,343 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 17:45:20,343 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:45:20,343 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 17:45:20,343 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 17:45:45,865 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:45:46,356 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:45:46,425 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:45:46,461 - etl_pipeline - ERROR - Staging completado (27 filas)
2025-05-31 17:45:46,461 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 17:45:46,462 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 17:45:46,462 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 17:45:46,471 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 17:45:46,471 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 17:45:46,474 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 17:45:46,474 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:45:46,474 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 17:45:46,474 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 17:57:50,065 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:57:50,622 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:57:50,687 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:57:50,729 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 17:57:50,729 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 17:57:50,732 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 17:57:50,732 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 17:57:50,740 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 17:57:50,743 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 17:57:50,749 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 17:57:50,782 - etl_pipeline - ERROR - Error en dim_mensajero: run_etl_with_staging() missing 1 required positional argument: 'table_name'
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\pipelines\etl_master.py", line 55, in execute
    success, _ = module.run_etl(truncate=True)
                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\pipelines\etl_dim_mensajero.py", line 10, in run_etl
    return run_etl_with_staging(
        extract_fn=run_extract,
    ...<3 lines>...
        truncate=truncate
    )
TypeError: run_etl_with_staging() missing 1 required positional argument: 'table_name'
2025-05-31 17:57:50,784 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:57:50,784 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 17:57:50,785 - etl_pipeline - INFO -   - DIM_MENSAJERO  : FALLÓ
2025-05-31 17:57:50,786 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 17:58:31,731 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:58:32,207 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:58:32,274 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:58:32,315 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 17:58:32,315 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 17:58:32,317 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 17:58:32,317 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 17:58:32,325 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 17:58:32,325 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 17:58:32,327 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 17:58:32,336 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 17:58:32,384 - etl_pipeline - ERROR - Error en extracción: (psycopg2.errors.SyntaxError) error de sintaxis en o cerca de «u»
LINE 5:             u.first_name AS nombre,
                    ^

[SQL: 
        SELECT 
            m.id AS cliente_mensajero_id,
            u.username AS nombre_usuario
            u.first_name AS nombre,
            u.last_name AS apellido,
            m.telefono,
            c.nombre AS ciudad_operacion,
            d.nombre AS departamento_operacion,
            m.activo
        FROM clientes_mensajeroaquitoy m
        JOIN auth_user u ON m.user_id = u.id
        LEFT JOIN ciudad c ON m.ciudad_operacion_id = c.ciudad_id
        LEFT JOIN departamento d ON c.departamento_id = d.departamento_id
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.SyntaxError: error de sintaxis en o cerca de «u»
LINE 5:             u.first_name AS nombre,
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\extract\extract_dim_mensajero.py", line 26, in run_extract
    df = pd.read_sql(query, session.connection())
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 734, in read_sql
    return pandas_sql.read_query(
           ~~~~~~~~~~~~~~~~~~~~~^
        sql,
        ^^^^
    ...<6 lines>...
        dtype=dtype,
        ^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1836, in read_query
    result = self.execute(sql, params)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1659, in execute
    return self.con.exec_driver_sql(sql, *args)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1775, in exec_driver_sql
    ret = self._execute_context(
        dialect,
    ...<5 lines>...
        distilled_parameters,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) error de sintaxis en o cerca de «u»
LINE 5:             u.first_name AS nombre,
                    ^

[SQL: 
        SELECT 
            m.id AS cliente_mensajero_id,
            u.username AS nombre_usuario
            u.first_name AS nombre,
            u.last_name AS apellido,
            m.telefono,
            c.nombre AS ciudad_operacion,
            d.nombre AS departamento_operacion,
            m.activo
        FROM clientes_mensajeroaquitoy m
        JOIN auth_user u ON m.user_id = u.id
        LEFT JOIN ciudad c ON m.ciudad_operacion_id = c.ciudad_id
        LEFT JOIN departamento d ON c.departamento_id = d.departamento_id
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-31 17:58:32,402 - etl_pipeline - ERROR - Falló la extracción o DataFrame vacío
2025-05-31 17:58:32,402 - etl_pipeline - INFO - ERROR DIM_MENSAJERO
2025-05-31 17:58:32,402 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:58:32,402 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 17:58:32,402 - etl_pipeline - INFO -   - DIM_MENSAJERO  : FALLÓ
2025-05-31 17:58:32,402 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 17:59:29,444 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 17:59:29,934 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 17:59:30,005 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 17:59:30,046 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 17:59:30,046 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 17:59:30,048 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 17:59:30,048 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 17:59:30,055 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 17:59:30,055 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 17:59:30,056 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 17:59:30,066 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 17:59:30,111 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 17:59:30,113 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 17:59:30,147 - etl_pipeline - ERROR - Error en staging: Could not reflect: requested table(s) not available in Engine(postgresql://postgres:***@localhost:5432/mensajeria_colombia_dw): (stg_dim_mensajero)
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\staging\staging_dim_mensajero.py", line 23, in run_staging
    df.to_sql('stg_dim_mensajero', session.connection(), if_exists='replace', index=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\core\generic.py", line 3087, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2008, in to_sql
    table = self.prep_table(
        frame=frame,
    ...<5 lines>...
        dtype=dtype,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1912, in prep_table
    table.create()
    ~~~~~~~~~~~~^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 988, in create
    self.pd_sql.drop_table(self.name, self.schema)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2059, in drop_table
    self.meta.reflect(
    ~~~~~~~~~~~~~~~~~^
        bind=self.con, only=[table_name], schema=schema, views=True
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\sql\schema.py", line 5873, in reflect
    raise exc.InvalidRequestError(
    ...<2 lines>...
    )
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(postgresql://postgres:***@localhost:5432/mensajeria_colombia_dw): (stg_dim_mensajero)
2025-05-31 17:59:30,152 - etl_pipeline - INFO - ERROR DIM_MENSAJERO
2025-05-31 17:59:30,152 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 17:59:30,153 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 17:59:30,153 - etl_pipeline - INFO -   - DIM_MENSAJERO  : FALLÓ
2025-05-31 17:59:30,153 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 18:03:18,638 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 18:03:19,233 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 18:03:19,304 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 18:03:19,341 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 18:03:19,341 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 18:03:19,342 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 18:03:19,342 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 18:03:19,348 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 18:03:19,348 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 18:03:19,350 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 18:03:19,359 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 18:03:19,394 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 18:03:19,396 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 18:03:19,431 - etl_pipeline - INFO - Staging completado (50 filas)
2025-05-31 18:03:19,432 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 18:03:19,433 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 18:03:19,434 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 18:03:19,448 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 18:03:19,448 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 18:03:19,449 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 18:03:19,449 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 18:03:19,449 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 18:03:19,449 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 18:03:19,449 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 18:05:42,729 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 18:05:43,290 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 18:05:43,358 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 18:05:43,405 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 18:05:43,405 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 18:05:43,406 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 18:05:43,406 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 18:05:43,414 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 18:05:43,414 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 18:05:43,416 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 18:05:43,439 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 18:05:43,480 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 18:05:43,482 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 18:05:43,521 - etl_pipeline - INFO - Staging completado (50 filas)
2025-05-31 18:05:43,522 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 18:05:43,523 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 18:05:43,523 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 18:05:43,532 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 18:05:43,532 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 18:05:43,534 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 18:05:43,534 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 18:05:43,534 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 18:05:43,534 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 18:05:43,534 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 18:08:08,436 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 18:08:09,011 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 18:08:09,081 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 18:08:09,118 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 18:08:09,118 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 18:08:09,119 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 18:08:09,119 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 18:08:09,132 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 18:08:09,133 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 18:08:09,133 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 18:08:09,135 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 18:08:09,199 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 18:08:09,200 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 18:08:09,236 - etl_pipeline - INFO - Staging completado (50 filas)
2025-05-31 18:08:09,236 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 18:08:09,238 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 18:08:09,238 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 18:08:09,250 - etl_pipeline - ERROR - Error en carga: (psycopg2.errors.UndefinedColumn) no existe la columna «cliente_mensajero_id» en la relación «dim_mensajero»
LINE 1: INSERT INTO dim_mensajero (mensajero_key, cliente_mensajero_...
                                                  ^

[SQL: INSERT INTO dim_mensajero (mensajero_key, cliente_mensajero_id, nombre_usuario, nombre, apellido, telefono, ciudad_operacion, departamento_operacion, activo) VALUES (%(mensajero_key__0)s, %(cliente_mensajero_id__0)s, %(nombre_usuario__0)s, %(nombre__ ... 9973 characters truncated ... o__49)s, %(telefono__49)s, %(ciudad_operacion__49)s, %(departamento_operacion__49)s, %(activo__49)s)]
[parameters: {'cliente_mensajero_id__0': 1, 'departamento_operacion__0': 'VALLE DEL CAUCA', 'activo__0': True, 'ciudad_operacion__0': 'ACOPI YUMBO', 'nombre_usuario__0': 'mensajero1', 'nombre__0': 'PEPITO_EL_RAPIDO', 'telefono__0': '310-300000', 'mensajero_key__0': 1, 'apellido__0': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__1': 2, 'departamento_operacion__1': None, 'activo__1': True, 'ciudad_operacion__1': None, 'nombre_usuario__1': 'mensajero2', 'nombre__1': 'PEPITO_EL_RAPIDO', 'telefono__1': '310-300000', 'mensajero_key__1': 2, 'apellido__1': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__2': 3, 'departamento_operacion__2': 'VALLE DEL CAUCA', 'activo__2': True, 'ciudad_operacion__2': 'CALI', 'nombre_usuario__2': 'Biil-Gates', 'nombre__2': 'PEPITO_EL_RAPIDO', 'telefono__2': '310-300000', 'mensajero_key__2': 3, 'apellido__2': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__3': 4, 'departamento_operacion__3': 'VALLE DEL CAUCA', 'activo__3': False, 'ciudad_operacion__3': 'CALI', 'nombre_usuario__3': 'Lionel_messi', 'nombre__3': 'PEPITO_EL_RAPIDO', 'telefono__3': '310-300000', 'mensajero_key__3': 4, 'apellido__3': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__4': 5, 'departamento_operacion__4': None, 'activo__4': True, 'ciudad_operacion__4': None, 'nombre_usuario__4': 'James Rodriguez', 'nombre__4': 'PEPITO_EL_RAPIDO', 'telefono__4': '310-300000', 'mensajero_key__4': 5, 'apellido__4': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__5': 6, 'departamento_operacion__5': None, 'activo__5': True, 'ciudad_operacion__5': None, 'nombre_usuario__5': 'mensajero_o' ... 350 parameters truncated ... 'nombre_usuario__44': 'HVARGAS', 'nombre__44': 'PEPITO_EL_RAPIDO', 'telefono__44': '310-300000', 'mensajero_key__44': 45, 'apellido__44': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__45': 48, 'departamento_operacion__45': 'VALLE DEL CAUCA', 'activo__45': True, 'ciudad_operacion__45': 'CALI', 'nombre_usuario__45': 'JULIANVILLANUEVA', 'nombre__45': 'PEPITO_EL_RAPIDO', 'telefono__45': '310-300000', 'mensajero_key__45': 46, 'apellido__45': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__46': 49, 'departamento_operacion__46': None, 'activo__46': True, 'ciudad_operacion__46': None, 'nombre_usuario__46': 'JSANCHEZ', 'nombre__46': 'PEPITO_EL_RAPIDO', 'telefono__46': '310-300000', 'mensajero_key__46': 47, 'apellido__46': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__47': 50, 'departamento_operacion__47': 'VALLE DEL CAUCA', 'activo__47': True, 'ciudad_operacion__47': 'CALI', 'nombre_usuario__47': 'MVERONICA', 'nombre__47': 'PEPITO_EL_RAPIDO', 'telefono__47': '310-300000', 'mensajero_key__47': 48, 'apellido__47': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__48': 83, 'departamento_operacion__48': 'VALLE DEL CAUCA', 'activo__48': True, 'ciudad_operacion__48': 'CALI', 'nombre_usuario__48': 'DANIELMAZUERA', 'nombre__48': 'PEPITO_EL_RAPIDO', 'telefono__48': '310-300000', 'mensajero_key__48': 49, 'apellido__48': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__49': 84, 'departamento_operacion__49': 'VALLE DEL CAUCA', 'activo__49': True, 'ciudad_operacion__49': 'CALI', 'nombre_usuario__49': 'WILSONMORALES', 'nombre__49': 'PEPITO_EL_RAPIDO', 'telefono__49': '310-300000', 'mensajero_key__49': 50, 'apellido__49': 'PEPITO_EL_FURIOSO'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2114, in _exec_insertmany_context
    dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~^
        cursor,
        ^^^^^^^
    ...<2 lines>...
        context,
        ^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: no existe la columna «cliente_mensajero_id» en la relación «dim_mensajero»
LINE 1: INSERT INTO dim_mensajero (mensajero_key, cliente_mensajero_...
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\load\load_dim_mensajero.py", line 29, in run_load
    df.to_sql(
    ~~~~~~~~~^
        'dim_mensajero',
        ^^^^^^^^^^^^^^^^
    ...<3 lines>...
        chunksize=1000
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\core\generic.py", line 3087, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2018, in to_sql
    total_inserted = sql_engine.insert_records(
        table=table,
    ...<7 lines>...
        **engine_kwargs,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1567, in insert_records
    raise err
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1558, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1119, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1010, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1840, in _execute_context
    return self._exec_insertmany_context(dialect, context)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2122, in _exec_insertmany_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e,
        ^^
    ...<4 lines>...
        is_sub_exec=True,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2114, in _exec_insertmany_context
    dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~^
        cursor,
        ^^^^^^^
    ...<2 lines>...
        context,
        ^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) no existe la columna «cliente_mensajero_id» en la relación «dim_mensajero»
LINE 1: INSERT INTO dim_mensajero (mensajero_key, cliente_mensajero_...
                                                  ^

[SQL: INSERT INTO dim_mensajero (mensajero_key, cliente_mensajero_id, nombre_usuario, nombre, apellido, telefono, ciudad_operacion, departamento_operacion, activo) VALUES (%(mensajero_key__0)s, %(cliente_mensajero_id__0)s, %(nombre_usuario__0)s, %(nombre__ ... 9973 characters truncated ... o__49)s, %(telefono__49)s, %(ciudad_operacion__49)s, %(departamento_operacion__49)s, %(activo__49)s)]
[parameters: {'cliente_mensajero_id__0': 1, 'departamento_operacion__0': 'VALLE DEL CAUCA', 'activo__0': True, 'ciudad_operacion__0': 'ACOPI YUMBO', 'nombre_usuario__0': 'mensajero1', 'nombre__0': 'PEPITO_EL_RAPIDO', 'telefono__0': '310-300000', 'mensajero_key__0': 1, 'apellido__0': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__1': 2, 'departamento_operacion__1': None, 'activo__1': True, 'ciudad_operacion__1': None, 'nombre_usuario__1': 'mensajero2', 'nombre__1': 'PEPITO_EL_RAPIDO', 'telefono__1': '310-300000', 'mensajero_key__1': 2, 'apellido__1': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__2': 3, 'departamento_operacion__2': 'VALLE DEL CAUCA', 'activo__2': True, 'ciudad_operacion__2': 'CALI', 'nombre_usuario__2': 'Biil-Gates', 'nombre__2': 'PEPITO_EL_RAPIDO', 'telefono__2': '310-300000', 'mensajero_key__2': 3, 'apellido__2': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__3': 4, 'departamento_operacion__3': 'VALLE DEL CAUCA', 'activo__3': False, 'ciudad_operacion__3': 'CALI', 'nombre_usuario__3': 'Lionel_messi', 'nombre__3': 'PEPITO_EL_RAPIDO', 'telefono__3': '310-300000', 'mensajero_key__3': 4, 'apellido__3': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__4': 5, 'departamento_operacion__4': None, 'activo__4': True, 'ciudad_operacion__4': None, 'nombre_usuario__4': 'James Rodriguez', 'nombre__4': 'PEPITO_EL_RAPIDO', 'telefono__4': '310-300000', 'mensajero_key__4': 5, 'apellido__4': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__5': 6, 'departamento_operacion__5': None, 'activo__5': True, 'ciudad_operacion__5': None, 'nombre_usuario__5': 'mensajero_o' ... 350 parameters truncated ... 'nombre_usuario__44': 'HVARGAS', 'nombre__44': 'PEPITO_EL_RAPIDO', 'telefono__44': '310-300000', 'mensajero_key__44': 45, 'apellido__44': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__45': 48, 'departamento_operacion__45': 'VALLE DEL CAUCA', 'activo__45': True, 'ciudad_operacion__45': 'CALI', 'nombre_usuario__45': 'JULIANVILLANUEVA', 'nombre__45': 'PEPITO_EL_RAPIDO', 'telefono__45': '310-300000', 'mensajero_key__45': 46, 'apellido__45': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__46': 49, 'departamento_operacion__46': None, 'activo__46': True, 'ciudad_operacion__46': None, 'nombre_usuario__46': 'JSANCHEZ', 'nombre__46': 'PEPITO_EL_RAPIDO', 'telefono__46': '310-300000', 'mensajero_key__46': 47, 'apellido__46': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__47': 50, 'departamento_operacion__47': 'VALLE DEL CAUCA', 'activo__47': True, 'ciudad_operacion__47': 'CALI', 'nombre_usuario__47': 'MVERONICA', 'nombre__47': 'PEPITO_EL_RAPIDO', 'telefono__47': '310-300000', 'mensajero_key__47': 48, 'apellido__47': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__48': 83, 'departamento_operacion__48': 'VALLE DEL CAUCA', 'activo__48': True, 'ciudad_operacion__48': 'CALI', 'nombre_usuario__48': 'DANIELMAZUERA', 'nombre__48': 'PEPITO_EL_RAPIDO', 'telefono__48': '310-300000', 'mensajero_key__48': 49, 'apellido__48': 'PEPITO_EL_FURIOSO', 'cliente_mensajero_id__49': 84, 'departamento_operacion__49': 'VALLE DEL CAUCA', 'activo__49': True, 'ciudad_operacion__49': 'CALI', 'nombre_usuario__49': 'WILSONMORALES', 'nombre__49': 'PEPITO_EL_RAPIDO', 'telefono__49': '310-300000', 'mensajero_key__49': 50, 'apellido__49': 'PEPITO_EL_FURIOSO'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-31 18:08:09,258 - etl_pipeline - INFO - ERROR DIM_MENSAJERO
2025-05-31 18:08:09,258 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 18:08:09,258 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 18:08:09,258 - etl_pipeline - INFO -   - DIM_MENSAJERO  : FALLÓ
2025-05-31 18:08:09,258 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 18:09:48,167 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 18:09:48,704 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 18:09:48,773 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 18:09:48,813 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 18:09:48,813 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 18:09:48,814 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 18:09:48,814 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 18:09:48,822 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 18:09:48,822 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 18:09:48,823 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 18:09:48,834 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 18:09:48,872 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 18:09:48,874 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 18:09:48,913 - etl_pipeline - INFO - Staging completado (50 filas)
2025-05-31 18:09:48,913 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 18:09:48,914 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 18:09:48,915 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 18:09:48,926 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 18:09:48,926 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 18:09:48,927 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 18:09:48,927 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 18:09:48,927 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 18:09:48,927 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 18:09:48,927 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 19:45:00,326 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 19:45:00,891 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 19:45:00,961 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 19:45:01,008 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 19:45:01,008 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 19:45:01,010 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 19:45:01,010 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 19:45:01,017 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 19:45:01,017 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 19:45:01,019 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 19:45:01,021 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 19:45:01,057 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 19:45:01,059 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 19:45:01,098 - etl_pipeline - INFO - Staging completado (50 filas)
2025-05-31 19:45:01,098 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 19:45:01,099 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 19:45:01,100 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 19:45:01,107 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 19:45:01,107 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 19:45:01,110 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 19:45:01,111 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 19:45:01,150 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 19:45:01,190 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 19:45:01,190 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 19:45:01,191 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 19:45:01,191 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 19:45:01,198 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 19:45:01,199 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_novedad
2025-05-31 19:45:01,200 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 19:45:01,200 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 19:45:01,200 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 19:45:01,201 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 19:45:01,201 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 19:45:01,201 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 19:47:45,692 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 19:47:46,287 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 19:47:46,355 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 19:47:46,393 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 19:47:46,393 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 19:47:46,394 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 19:47:46,394 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 19:47:46,402 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 19:47:46,402 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 19:47:46,404 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 19:47:46,406 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 19:47:46,443 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 19:47:46,445 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 19:47:46,483 - etl_pipeline - INFO - Staging completado (50 filas)
2025-05-31 19:47:46,483 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 19:47:46,485 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 19:47:46,485 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 19:47:46,496 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 19:47:46,497 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 19:47:46,501 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 19:47:46,518 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 19:47:46,662 - etl_pipeline - ERROR - Error extrayendo los datos para dim_novedad
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.FeatureNotSupported: no están implementadas las referencias entre bases de datos: «public.public.mensajeria_tiponovedad»
LINE 5:         FROM public.public.mensajeria_tiponovedad tn
                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\extract\extract_dim_novedad.py", line 19, in run_extract
    return pd.read_sql(query, session.connection()), True
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 734, in read_sql
    return pandas_sql.read_query(
           ~~~~~~~~~~~~~~~~~~~~~^
        sql,
        ^^^^
    ...<6 lines>...
        dtype=dtype,
        ^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1836, in read_query
    result = self.execute(sql, params)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1659, in execute
    return self.con.exec_driver_sql(sql, *args)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1775, in exec_driver_sql
    ret = self._execute_context(
        dialect,
    ...<5 lines>...
        distilled_parameters,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.NotSupportedError: (psycopg2.errors.FeatureNotSupported) no están implementadas las referencias entre bases de datos: «public.public.mensajeria_tiponovedad»
LINE 5:         FROM public.public.mensajeria_tiponovedad tn
                     ^

[SQL: 
        SELECT
            tn.id AS novedad_id,
            tn.nombre
        FROM public.public.mensajeria_tiponovedad tn
        ]
(Background on this error at: https://sqlalche.me/e/20/tw8g)
2025-05-31 19:47:46,666 - etl_pipeline - ERROR - Falló la extracción o DataFrame vacío
2025-05-31 19:47:46,666 - etl_pipeline - INFO - ERROR DIM_NOVEDAD
2025-05-31 19:47:46,666 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 19:47:46,666 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 19:47:46,667 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 19:47:46,667 - etl_pipeline - INFO -   - DIM_NOVEDAD    : FALLÓ
2025-05-31 19:47:46,667 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 19:49:28,130 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 19:49:28,704 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 19:49:28,771 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 19:49:28,808 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 19:49:28,808 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 19:49:28,810 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 19:49:28,810 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 19:49:28,817 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 19:49:28,817 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 19:49:28,819 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 19:49:28,820 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 19:49:28,855 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 19:49:28,857 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 19:49:28,899 - etl_pipeline - INFO - Staging completado (50 filas)
2025-05-31 19:49:28,899 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 19:49:28,900 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 19:49:28,901 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 19:49:28,909 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 19:49:28,909 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 19:49:28,911 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 19:49:28,922 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 19:49:29,079 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 19:49:29,115 - etl_pipeline - ERROR - Error creando tabla stg_dim_novedad
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.SyntaxError: error de sintaxis en o cerca de «)»
LINE 5:         ) ON COMMIT PRESERVE ROWS;
                ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\staging\staging_dim_novedad.py", line 14, in run_staging
    session.execute(text("""
    ~~~~~~~~~~~~~~~^^^^^^^^^
    CREATE TEMPORARY TABLE stg_dim_novedad (
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    ) ON COMMIT PRESERVE ROWS;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
    """))
    ^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2260, in _execute_internal
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) error de sintaxis en o cerca de «)»
LINE 5:         ) ON COMMIT PRESERVE ROWS;
                ^

[SQL: 
        CREATE TEMPORARY TABLE stg_dim_novedad (
            novedad_id INTEGER NOT NULL,
            nombre VARCHAR(30) NOT NULL,
        ) ON COMMIT PRESERVE ROWS;
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-31 19:49:29,120 - etl_pipeline - INFO - ERROR DIM_NOVEDAD
2025-05-31 19:49:29,120 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 19:49:29,120 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 19:49:29,120 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 19:49:29,120 - etl_pipeline - INFO -   - DIM_NOVEDAD    : FALLÓ
2025-05-31 19:49:29,120 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 19:49:53,142 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 19:49:53,609 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 19:49:53,678 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 19:49:53,830 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 19:49:53,830 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 19:49:53,832 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 19:49:53,832 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 19:49:53,839 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 19:49:53,839 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 19:49:53,840 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 19:49:53,842 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 19:49:53,878 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 19:49:53,880 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 19:49:53,917 - etl_pipeline - INFO - Staging completado (50 filas)
2025-05-31 19:49:53,918 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 19:49:53,919 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 19:49:53,919 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 19:49:53,935 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 19:49:53,935 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 19:49:53,938 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 19:49:53,958 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 19:49:54,006 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 19:49:54,047 - etl_pipeline - INFO - Staging completado (2 filas)
2025-05-31 19:49:54,048 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 19:49:54,049 - etl_pipeline - ERROR - Error en transformación: (psycopg2.errors.SyntaxError) error de sintaxis en o cerca de «FROM»
LINE 5:         FROM pg_temp.stg_dim_cliente
                ^

[SQL: 
        SELECT 
            ROW_NUMBER() OVER (ORDER BY novedad_id) AS novedad_key,
            UPPER(TRIM(nombre)) AS nombre,
        FROM pg_temp.stg_dim_cliente
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.SyntaxError: error de sintaxis en o cerca de «FROM»
LINE 5:         FROM pg_temp.stg_dim_cliente
                ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\transform\transform_dim_novedad.py", line 16, in run_transform
    df = pd.read_sql(query, session.connection())
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 734, in read_sql
    return pandas_sql.read_query(
           ~~~~~~~~~~~~~~~~~~~~~^
        sql,
        ^^^^
    ...<6 lines>...
        dtype=dtype,
        ^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1836, in read_query
    result = self.execute(sql, params)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1660, in execute
    return self.con.execute(sql, *args)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) error de sintaxis en o cerca de «FROM»
LINE 5:         FROM pg_temp.stg_dim_cliente
                ^

[SQL: 
        SELECT 
            ROW_NUMBER() OVER (ORDER BY novedad_id) AS novedad_key,
            UPPER(TRIM(nombre)) AS nombre,
        FROM pg_temp.stg_dim_cliente
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-31 19:49:54,054 - etl_pipeline - INFO - ERROR DIM_NOVEDAD
2025-05-31 19:49:54,054 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 19:49:54,054 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 19:49:54,054 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 19:49:54,055 - etl_pipeline - INFO -   - DIM_NOVEDAD    : FALLÓ
2025-05-31 19:49:54,055 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 19:50:56,105 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 19:50:56,585 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 19:50:56,655 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 19:50:56,693 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 19:50:56,693 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 19:50:56,694 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 19:50:56,694 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 19:50:56,701 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 19:50:56,701 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 19:50:56,703 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 19:50:56,705 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 19:50:56,740 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 19:50:56,742 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 19:50:56,782 - etl_pipeline - INFO - Staging completado (50 filas)
2025-05-31 19:50:56,782 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 19:50:56,784 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 19:50:56,784 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 19:50:56,791 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 19:50:56,791 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 19:50:56,793 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 19:50:56,795 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 19:50:56,827 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 19:50:56,858 - etl_pipeline - INFO - Staging completado (2 filas)
2025-05-31 19:50:56,858 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 19:50:56,859 - etl_pipeline - ERROR - Error en transformación: (psycopg2.errors.SyntaxError) error de sintaxis en o cerca de «FROM»
LINE 5:         FROM pg_temp.stg_dim_cliente
                ^

[SQL: 
        SELECT 
            ROW_NUMBER() OVER (ORDER BY novedad_id) AS novedad_key,
            UPPER(TRIM(nombre)) AS nombre,
        FROM pg_temp.stg_dim_cliente
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.SyntaxError: error de sintaxis en o cerca de «FROM»
LINE 5:         FROM pg_temp.stg_dim_cliente
                ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\transform\transform_dim_novedad.py", line 16, in run_transform
    df = pd.read_sql(query, session.connection())
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 734, in read_sql
    return pandas_sql.read_query(
           ~~~~~~~~~~~~~~~~~~~~~^
        sql,
        ^^^^
    ...<6 lines>...
        dtype=dtype,
        ^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1836, in read_query
    result = self.execute(sql, params)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1660, in execute
    return self.con.execute(sql, *args)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) error de sintaxis en o cerca de «FROM»
LINE 5:         FROM pg_temp.stg_dim_cliente
                ^

[SQL: 
        SELECT 
            ROW_NUMBER() OVER (ORDER BY novedad_id) AS novedad_key,
            UPPER(TRIM(nombre)) AS nombre,
        FROM pg_temp.stg_dim_cliente
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-31 19:50:56,863 - etl_pipeline - INFO - ERROR DIM_NOVEDAD
2025-05-31 19:50:56,863 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 19:50:56,864 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 19:50:56,864 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 19:50:56,864 - etl_pipeline - INFO -   - DIM_NOVEDAD    : FALLÓ
2025-05-31 19:50:56,864 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 19:51:18,336 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 19:51:18,817 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 19:51:19,016 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 19:51:19,054 - etl_pipeline - INFO - Staging completado (27 filas)
2025-05-31 19:51:19,054 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 19:51:19,055 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 19:51:19,056 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 19:51:19,063 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 19:51:19,063 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 19:51:19,065 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 19:51:19,066 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 19:51:19,111 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 19:51:19,112 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 19:51:19,149 - etl_pipeline - INFO - Staging completado (50 filas)
2025-05-31 19:51:19,149 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 19:51:19,150 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 19:51:19,151 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 19:51:19,158 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 19:51:19,158 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 19:51:19,160 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 19:51:19,172 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 19:51:19,210 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 19:51:19,240 - etl_pipeline - INFO - Staging completado (2 filas)
2025-05-31 19:51:19,241 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 19:51:19,242 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 19:51:19,242 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 19:51:19,248 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 19:51:19,248 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 19:51:19,249 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 19:51:19,249 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 19:51:19,249 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 19:51:19,249 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 19:51:19,249 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 19:51:19,249 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 21:05:45,076 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 21:05:46,043 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 21:05:46,156 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 21:05:46,216 - etl_pipeline - INFO - Staging stg_dim_cliente completado (27 filas)
2025-05-31 21:05:46,216 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 21:05:46,218 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 21:05:46,218 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 21:05:46,237 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 21:05:46,238 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 21:05:46,241 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 21:05:46,245 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 21:05:46,301 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 21:05:46,304 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 21:05:46,365 - etl_pipeline - INFO - Staging stg_dim_mensajero completado (50 filas)
2025-05-31 21:05:46,365 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 21:05:46,368 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 21:05:46,368 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 21:05:46,380 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 21:05:46,381 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 21:05:46,387 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 21:05:46,394 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 21:05:46,577 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 21:05:46,635 - etl_pipeline - INFO - Staging stg_dim_novedad completado (2 filas)
2025-05-31 21:05:46,635 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 21:05:46,637 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 21:05:46,638 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 21:05:46,647 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 21:05:46,647 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 21:05:46,652 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 21:05:46,673 - etl_pipeline - INFO - Extrayendo datos... dim_estado_servicio
2025-05-31 21:05:46,734 - etl_pipeline - INFO - Cargando a staging ... dim_estado_servicio
2025-05-31 21:05:46,797 - etl_pipeline - INFO - Staging stg_dim_estado_servicio completado (6 filas)
2025-05-31 21:05:46,798 - etl_pipeline - INFO - Transformando... dim_estado_servicio
2025-05-31 21:05:46,799 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 21:05:46,800 - etl_pipeline - INFO - Cargando a destino... dim_estado_servicio
2025-05-31 21:05:46,817 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 21:05:46,817 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_estado_servicio
2025-05-31 21:05:46,819 - etl_pipeline - INFO - SUCCESS DIM_ESTADO_SERVICIO
2025-05-31 21:05:46,819 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 21:05:46,819 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 21:05:46,819 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 21:05:46,820 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 21:05:46,820 - etl_pipeline - INFO -   - DIM_ESTADO_SERVICIO: ÉXITO
2025-05-31 21:05:46,821 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 21:22:56,840 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 21:22:57,712 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 21:22:57,812 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 21:22:57,862 - etl_pipeline - INFO - Staging stg_dim_cliente completado (27 filas)
2025-05-31 21:22:57,862 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 21:22:57,864 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 21:22:57,864 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 21:22:57,874 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 21:22:57,874 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 21:22:57,876 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 21:22:57,878 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 21:22:57,930 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 21:22:57,932 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 21:22:57,985 - etl_pipeline - INFO - Staging stg_dim_mensajero completado (50 filas)
2025-05-31 21:22:57,986 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 21:22:57,988 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 21:22:57,988 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 21:22:58,000 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 21:22:58,000 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 21:22:58,003 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 21:22:58,006 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 21:22:58,056 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 21:22:58,107 - etl_pipeline - INFO - Staging stg_dim_novedad completado (2 filas)
2025-05-31 21:22:58,107 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 21:22:58,109 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 21:22:58,109 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 21:22:58,117 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 21:22:58,117 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 21:22:58,122 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 21:22:58,139 - etl_pipeline - INFO - Extrayendo datos... dim_estado_servicio
2025-05-31 21:22:58,187 - etl_pipeline - INFO - Cargando a staging ... dim_estado_servicio
2025-05-31 21:22:58,246 - etl_pipeline - INFO - Staging stg_dim_estado_servicio completado (6 filas)
2025-05-31 21:22:58,246 - etl_pipeline - INFO - Transformando... dim_estado_servicio
2025-05-31 21:22:58,248 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 21:22:58,248 - etl_pipeline - INFO - Cargando a destino... dim_estado_servicio
2025-05-31 21:22:58,255 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 21:22:58,255 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_estado_servicio
2025-05-31 21:22:58,259 - etl_pipeline - INFO - SUCCESS DIM_ESTADO_SERVICIO
2025-05-31 21:22:58,290 - etl_pipeline - INFO - Extrayendo datos... dim_tipo_servicio
2025-05-31 21:22:58,338 - etl_pipeline - INFO - Cargando a staging ... dim_tipo_servicio
2025-05-31 21:22:58,392 - etl_pipeline - INFO - Staging stg_dim_tipo_servicio completado (6 filas)
2025-05-31 21:22:58,392 - etl_pipeline - INFO - Transformando... dim_tipo_servicio
2025-05-31 21:22:58,394 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 21:22:58,394 - etl_pipeline - INFO - Cargando a destino... dim_tipo_servicio
2025-05-31 21:22:58,410 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 21:22:58,410 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_tipo_servicio
2025-05-31 21:22:58,412 - etl_pipeline - INFO - SUCCESS DIM_TIPO_SERVICIO
2025-05-31 21:22:58,412 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 21:22:58,412 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 21:22:58,412 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 21:22:58,412 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 21:22:58,412 - etl_pipeline - INFO -   - DIM_ESTADO_SERVICIO: ÉXITO
2025-05-31 21:22:58,413 - etl_pipeline - INFO -   - DIM_TIPO_SERVICIO: ÉXITO
2025-05-31 21:22:58,413 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 21:24:06,734 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 21:24:07,505 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 21:24:07,606 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 21:24:07,659 - etl_pipeline - INFO - Staging stg_dim_cliente completado (27 filas)
2025-05-31 21:24:07,659 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 21:24:07,662 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 21:24:07,662 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 21:24:07,673 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 21:24:07,674 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 21:24:07,676 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 21:24:07,679 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 21:24:07,727 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 21:24:07,730 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 21:24:07,787 - etl_pipeline - INFO - Staging stg_dim_mensajero completado (50 filas)
2025-05-31 21:24:07,788 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 21:24:07,790 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 21:24:07,790 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 21:24:07,800 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 21:24:07,801 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 21:24:07,803 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 21:24:07,805 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 21:24:07,979 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 21:24:08,036 - etl_pipeline - INFO - Staging stg_dim_novedad completado (2 filas)
2025-05-31 21:24:08,036 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 21:24:08,038 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 21:24:08,038 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 21:24:08,048 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 21:24:08,048 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 21:24:08,052 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 21:24:08,057 - etl_pipeline - INFO - Extrayendo datos... dim_estado_servicio
2025-05-31 21:24:08,109 - etl_pipeline - INFO - Cargando a staging ... dim_estado_servicio
2025-05-31 21:24:08,298 - etl_pipeline - INFO - Staging stg_dim_estado_servicio completado (6 filas)
2025-05-31 21:24:08,298 - etl_pipeline - INFO - Transformando... dim_estado_servicio
2025-05-31 21:24:08,300 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 21:24:08,300 - etl_pipeline - INFO - Cargando a destino... dim_estado_servicio
2025-05-31 21:24:08,309 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 21:24:08,309 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_estado_servicio
2025-05-31 21:24:08,313 - etl_pipeline - INFO - SUCCESS DIM_ESTADO_SERVICIO
2025-05-31 21:24:08,328 - etl_pipeline - INFO - Extrayendo datos... dim_tipo_servicio
2025-05-31 21:24:08,386 - etl_pipeline - INFO - Cargando a staging ... dim_tipo_servicio
2025-05-31 21:24:08,568 - etl_pipeline - INFO - Staging stg_dim_tipo_servicio completado (4 filas)
2025-05-31 21:24:08,568 - etl_pipeline - INFO - Transformando... dim_tipo_servicio
2025-05-31 21:24:08,570 - etl_pipeline - INFO - Transformación completada (4 filas)
2025-05-31 21:24:08,570 - etl_pipeline - INFO - Cargando a destino... dim_tipo_servicio
2025-05-31 21:24:08,582 - etl_pipeline - INFO - Carga exitosa. Total registros: 4
2025-05-31 21:24:08,583 - etl_pipeline - INFO - ETL completado. Filas cargadas: 4 en dim_tipo_servicio
2025-05-31 21:24:08,588 - etl_pipeline - INFO - SUCCESS DIM_TIPO_SERVICIO
2025-05-31 21:24:08,589 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 21:24:08,589 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 21:24:08,589 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 21:24:08,590 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 21:24:08,590 - etl_pipeline - INFO -   - DIM_ESTADO_SERVICIO: ÉXITO
2025-05-31 21:24:08,590 - etl_pipeline - INFO -   - DIM_TIPO_SERVICIO: ÉXITO
2025-05-31 21:24:08,590 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 22:56:37,046 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 22:56:38,010 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 22:56:38,139 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 22:56:38,206 - etl_pipeline - INFO - Staging stg_dim_cliente completado (27 filas)
2025-05-31 22:56:38,206 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 22:56:38,209 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 22:56:38,209 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 22:56:38,240 - etl_pipeline - ERROR - Error en carga: (psycopg2.errors.NotNullViolation) el valor nulo en la columna «cliente_id» de la relación «dim_cliente» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (1, null, 25, CLIENTE 2, algo.com, Calle 100 No 25-18, 327-00000, CALI, VALLE DEL CAUCA, S, t, 2025-05-31 22:56:38.183616).

[SQL: INSERT INTO dim_cliente (cliente_key, nit, nombre, email, direccion, telefono, ciudad, departamento, sector, activo) VALUES (%(cliente_key__0)s, %(nit__0)s, %(nombre__0)s, %(email__0)s, %(direccion__0)s, %(telefono__0)s, %(ciudad__0)s, %(departamento ... 4370 characters truncated ... ccion__26)s, %(telefono__26)s, %(ciudad__26)s, %(departamento__26)s, %(sector__26)s, %(activo__26)s)]
[parameters: {'activo__0': True, 'direccion__0': 'Calle 100 No 25-18', 'email__0': 'algo.com', 'cliente_key__0': 1, 'telefono__0': '327-00000', 'departamento__0': 'VALLE DEL CAUCA', 'ciudad__0': 'CALI', 'sector__0': 'S', 'nombre__0': 'CLIENTE 2', 'nit__0': '25', 'activo__1': True, 'direccion__1': 'Calle 100 No 25-18', 'email__1': 'algo.com', 'cliente_key__1': 2, 'telefono__1': '327-00000', 'departamento__1': 'VALLE DEL CAUCA', 'ciudad__1': 'CALI', 'sector__1': 'INDUSTRIAL', 'nombre__1': 'CLIENTE 1', 'nit__1': '123', 'activo__2': True, 'direccion__2': 'Calle 100 No 25-18', 'email__2': 'algo.com', 'cliente_key__2': 3, 'telefono__2': '327-00000', 'departamento__2': 'VALLE DEL CAUCA', 'ciudad__2': 'CALI', 'sector__2': 'SALUD', 'nombre__2': 'BANCO REGIONAL  DE SANGRE BLOD-LIFE', 'nit__2': '312289-5', 'activo__3': True, 'direccion__3': 'Calle 100 No 25-18', 'email__3': 'algo.com', 'cliente_key__3': 4, 'telefono__3': '327-00000', 'departamento__3': 'VALLE DEL CAUCA', 'ciudad__3': 'CALI', 'sector__3': 'SALUD', 'nombre__3': 'CRUZ AZUL-LIFE', 'nit__3': '306215-0', 'activo__4': True, 'direccion__4': 'Calle 100 No 25-18', 'email__4': 'algo.com', 'cliente_key__4': 5, 'telefono__4': '327-00000', 'departamento__4': 'VALLE DEL CAUCA', 'ciudad__4': 'CALI', 'sector__4': 'SALUD', 'nombre__4': 'CLINICA CALI -JOVEN', 'nit__4': '300513-3' ... 170 parameters truncated ... 'activo__22': True, 'direccion__22': 'Calle 100 No 25-18', 'email__22': 'algo.com', 'cliente_key__22': 23, 'telefono__22': '327-00000', 'departamento__22': 'VALLE DEL CAUCA', 'ciudad__22': 'CALI', 'sector__22': 'SALUD', 'nombre__22': 'CLINICA MEDICA S.A.S', 'nit__22': '900603', 'activo__23': True, 'direccion__23': 'Calle 100 No 25-18', 'email__23': 'algo.com', 'cliente_key__23': 24, 'telefono__23': '327-00000', 'departamento__23': 'VALLE DEL CAUCA', 'ciudad__23': 'CALI', 'sector__23': 'SALUD', 'nombre__23': 'CLINICA SAN RAFAEL DE OCCIDENTE', 'nit__23': '9009754', 'activo__24': True, 'direccion__24': 'Calle 100 No 25-18', 'email__24': 'algo.com', 'cliente_key__24': 25, 'telefono__24': '327-00000', 'departamento__24': 'VALLE DEL CAUCA', 'ciudad__24': 'CALI', 'sector__24': 'SALUD', 'nombre__24': 'CALI SULUD Y VIDA', 'nit__24': '900361', 'activo__25': True, 'direccion__25': 'Calle 100 No 25-18', 'email__25': 'algo.com', 'cliente_key__25': 26, 'telefono__25': '327-00000', 'departamento__25': 'VALLE DEL CAUCA', 'ciudad__25': 'CALI', 'sector__25': 'SALUD', 'nombre__25': 'OCCIDENTE DE SALUD-CALI', 'nit__25': '25478', 'activo__26': True, 'direccion__26': 'Calle 100 No 25-18', 'email__26': 'algo.com', 'cliente_key__26': 27, 'telefono__26': '327-00000', 'departamento__26': 'VALLE DEL CAUCA', 'ciudad__26': 'CALI', 'sector__26': 'INDUSTRIAL', 'nombre__26': 'MEDICOS Y SALUD', 'nit__26': '201478'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2114, in _exec_insertmany_context
    dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~^
        cursor,
        ^^^^^^^
    ...<2 lines>...
        context,
        ^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: el valor nulo en la columna «cliente_id» de la relación «dim_cliente» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (1, null, 25, CLIENTE 2, algo.com, Calle 100 No 25-18, 327-00000, CALI, VALLE DEL CAUCA, S, t, 2025-05-31 22:56:38.183616).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\load\load_dim_cliente.py", line 34, in run_load
    df.to_sql(
    ~~~~~~~~~^
        'dim_cliente',
        ^^^^^^^^^^^^^^
    ...<3 lines>...
        chunksize=1000
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\core\generic.py", line 3087, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2018, in to_sql
    total_inserted = sql_engine.insert_records(
        table=table,
    ...<7 lines>...
        **engine_kwargs,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1567, in insert_records
    raise err
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1558, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1119, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1010, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1840, in _execute_context
    return self._exec_insertmany_context(dialect, context)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2122, in _exec_insertmany_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e,
        ^^
    ...<4 lines>...
        is_sub_exec=True,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2114, in _exec_insertmany_context
    dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~^
        cursor,
        ^^^^^^^
    ...<2 lines>...
        context,
        ^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) el valor nulo en la columna «cliente_id» de la relación «dim_cliente» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (1, null, 25, CLIENTE 2, algo.com, Calle 100 No 25-18, 327-00000, CALI, VALLE DEL CAUCA, S, t, 2025-05-31 22:56:38.183616).

[SQL: INSERT INTO dim_cliente (cliente_key, nit, nombre, email, direccion, telefono, ciudad, departamento, sector, activo) VALUES (%(cliente_key__0)s, %(nit__0)s, %(nombre__0)s, %(email__0)s, %(direccion__0)s, %(telefono__0)s, %(ciudad__0)s, %(departamento ... 4370 characters truncated ... ccion__26)s, %(telefono__26)s, %(ciudad__26)s, %(departamento__26)s, %(sector__26)s, %(activo__26)s)]
[parameters: {'activo__0': True, 'direccion__0': 'Calle 100 No 25-18', 'email__0': 'algo.com', 'cliente_key__0': 1, 'telefono__0': '327-00000', 'departamento__0': 'VALLE DEL CAUCA', 'ciudad__0': 'CALI', 'sector__0': 'S', 'nombre__0': 'CLIENTE 2', 'nit__0': '25', 'activo__1': True, 'direccion__1': 'Calle 100 No 25-18', 'email__1': 'algo.com', 'cliente_key__1': 2, 'telefono__1': '327-00000', 'departamento__1': 'VALLE DEL CAUCA', 'ciudad__1': 'CALI', 'sector__1': 'INDUSTRIAL', 'nombre__1': 'CLIENTE 1', 'nit__1': '123', 'activo__2': True, 'direccion__2': 'Calle 100 No 25-18', 'email__2': 'algo.com', 'cliente_key__2': 3, 'telefono__2': '327-00000', 'departamento__2': 'VALLE DEL CAUCA', 'ciudad__2': 'CALI', 'sector__2': 'SALUD', 'nombre__2': 'BANCO REGIONAL  DE SANGRE BLOD-LIFE', 'nit__2': '312289-5', 'activo__3': True, 'direccion__3': 'Calle 100 No 25-18', 'email__3': 'algo.com', 'cliente_key__3': 4, 'telefono__3': '327-00000', 'departamento__3': 'VALLE DEL CAUCA', 'ciudad__3': 'CALI', 'sector__3': 'SALUD', 'nombre__3': 'CRUZ AZUL-LIFE', 'nit__3': '306215-0', 'activo__4': True, 'direccion__4': 'Calle 100 No 25-18', 'email__4': 'algo.com', 'cliente_key__4': 5, 'telefono__4': '327-00000', 'departamento__4': 'VALLE DEL CAUCA', 'ciudad__4': 'CALI', 'sector__4': 'SALUD', 'nombre__4': 'CLINICA CALI -JOVEN', 'nit__4': '300513-3' ... 170 parameters truncated ... 'activo__22': True, 'direccion__22': 'Calle 100 No 25-18', 'email__22': 'algo.com', 'cliente_key__22': 23, 'telefono__22': '327-00000', 'departamento__22': 'VALLE DEL CAUCA', 'ciudad__22': 'CALI', 'sector__22': 'SALUD', 'nombre__22': 'CLINICA MEDICA S.A.S', 'nit__22': '900603', 'activo__23': True, 'direccion__23': 'Calle 100 No 25-18', 'email__23': 'algo.com', 'cliente_key__23': 24, 'telefono__23': '327-00000', 'departamento__23': 'VALLE DEL CAUCA', 'ciudad__23': 'CALI', 'sector__23': 'SALUD', 'nombre__23': 'CLINICA SAN RAFAEL DE OCCIDENTE', 'nit__23': '9009754', 'activo__24': True, 'direccion__24': 'Calle 100 No 25-18', 'email__24': 'algo.com', 'cliente_key__24': 25, 'telefono__24': '327-00000', 'departamento__24': 'VALLE DEL CAUCA', 'ciudad__24': 'CALI', 'sector__24': 'SALUD', 'nombre__24': 'CALI SULUD Y VIDA', 'nit__24': '900361', 'activo__25': True, 'direccion__25': 'Calle 100 No 25-18', 'email__25': 'algo.com', 'cliente_key__25': 26, 'telefono__25': '327-00000', 'departamento__25': 'VALLE DEL CAUCA', 'ciudad__25': 'CALI', 'sector__25': 'SALUD', 'nombre__25': 'OCCIDENTE DE SALUD-CALI', 'nit__25': '25478', 'activo__26': True, 'direccion__26': 'Calle 100 No 25-18', 'email__26': 'algo.com', 'cliente_key__26': 27, 'telefono__26': '327-00000', 'departamento__26': 'VALLE DEL CAUCA', 'ciudad__26': 'CALI', 'sector__26': 'INDUSTRIAL', 'nombre__26': 'MEDICOS Y SALUD', 'nit__26': '201478'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-05-31 22:56:38,255 - etl_pipeline - INFO - ERROR DIM_CLIENTE
2025-05-31 22:56:38,260 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 22:56:38,453 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 22:56:38,455 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 22:56:38,517 - etl_pipeline - INFO - Staging stg_dim_mensajero completado (50 filas)
2025-05-31 22:56:38,517 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 22:56:38,519 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 22:56:38,519 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 22:56:38,533 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 22:56:38,533 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 22:56:38,537 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 22:56:38,544 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 22:56:38,597 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 22:56:38,651 - etl_pipeline - INFO - Staging stg_dim_novedad completado (2 filas)
2025-05-31 22:56:38,652 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 22:56:38,654 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 22:56:38,655 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 22:56:38,663 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 22:56:38,663 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 22:56:38,667 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 22:56:38,672 - etl_pipeline - INFO - Extrayendo datos... dim_estado_servicio
2025-05-31 22:56:38,729 - etl_pipeline - INFO - Cargando a staging ... dim_estado_servicio
2025-05-31 22:56:38,915 - etl_pipeline - INFO - Staging stg_dim_estado_servicio completado (6 filas)
2025-05-31 22:56:38,916 - etl_pipeline - INFO - Transformando... dim_estado_servicio
2025-05-31 22:56:38,918 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 22:56:38,918 - etl_pipeline - INFO - Cargando a destino... dim_estado_servicio
2025-05-31 22:56:38,930 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 22:56:38,930 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_estado_servicio
2025-05-31 22:56:38,936 - etl_pipeline - INFO - SUCCESS DIM_ESTADO_SERVICIO
2025-05-31 22:56:38,943 - etl_pipeline - INFO - Extrayendo datos... dim_tipo_servicio
2025-05-31 22:56:39,002 - etl_pipeline - INFO - Cargando a staging ... dim_tipo_servicio
2025-05-31 22:56:39,063 - etl_pipeline - INFO - Staging stg_dim_tipo_servicio completado (4 filas)
2025-05-31 22:56:39,064 - etl_pipeline - INFO - Transformando... dim_tipo_servicio
2025-05-31 22:56:39,066 - etl_pipeline - INFO - Transformación completada (4 filas)
2025-05-31 22:56:39,066 - etl_pipeline - INFO - Cargando a destino... dim_tipo_servicio
2025-05-31 22:56:39,076 - etl_pipeline - INFO - Carga exitosa. Total registros: 4
2025-05-31 22:56:39,076 - etl_pipeline - INFO - ETL completado. Filas cargadas: 4 en dim_tipo_servicio
2025-05-31 22:56:39,081 - etl_pipeline - INFO - SUCCESS DIM_TIPO_SERVICIO
2025-05-31 22:56:39,082 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 22:56:39,082 - etl_pipeline - INFO -   - DIM_CLIENTE    : FALLÓ
2025-05-31 22:56:39,082 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 22:56:39,083 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 22:56:39,083 - etl_pipeline - INFO -   - DIM_ESTADO_SERVICIO: ÉXITO
2025-05-31 22:56:39,083 - etl_pipeline - INFO -   - DIM_TIPO_SERVICIO: ÉXITO
2025-05-31 22:56:39,083 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 22:57:51,116 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 22:57:51,926 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 22:57:52,043 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 22:57:52,113 - etl_pipeline - INFO - Staging stg_dim_cliente completado (27 filas)
2025-05-31 22:57:52,113 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 22:57:52,116 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 22:57:52,116 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 22:57:52,145 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 22:57:52,145 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 22:57:52,146 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 22:57:52,151 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 22:57:52,207 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 22:57:52,210 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 22:57:52,269 - etl_pipeline - INFO - Staging stg_dim_mensajero completado (50 filas)
2025-05-31 22:57:52,270 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 22:57:52,272 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 22:57:52,272 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 22:57:52,283 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 22:57:52,283 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 22:57:52,286 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 22:57:52,289 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 22:57:52,334 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 22:57:52,377 - etl_pipeline - INFO - Staging stg_dim_novedad completado (2 filas)
2025-05-31 22:57:52,377 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 22:57:52,379 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 22:57:52,379 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 22:57:52,385 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 22:57:52,385 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 22:57:52,388 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 22:57:52,390 - etl_pipeline - INFO - Extrayendo datos... dim_estado_servicio
2025-05-31 22:57:52,440 - etl_pipeline - INFO - Cargando a staging ... dim_estado_servicio
2025-05-31 22:57:52,491 - etl_pipeline - INFO - Staging stg_dim_estado_servicio completado (6 filas)
2025-05-31 22:57:52,491 - etl_pipeline - INFO - Transformando... dim_estado_servicio
2025-05-31 22:57:52,493 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 22:57:52,493 - etl_pipeline - INFO - Cargando a destino... dim_estado_servicio
2025-05-31 22:57:52,499 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 22:57:52,500 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_estado_servicio
2025-05-31 22:57:52,502 - etl_pipeline - INFO - SUCCESS DIM_ESTADO_SERVICIO
2025-05-31 22:57:52,504 - etl_pipeline - INFO - Extrayendo datos... dim_tipo_servicio
2025-05-31 22:57:52,550 - etl_pipeline - INFO - Cargando a staging ... dim_tipo_servicio
2025-05-31 22:57:52,597 - etl_pipeline - INFO - Staging stg_dim_tipo_servicio completado (4 filas)
2025-05-31 22:57:52,597 - etl_pipeline - INFO - Transformando... dim_tipo_servicio
2025-05-31 22:57:52,599 - etl_pipeline - INFO - Transformación completada (4 filas)
2025-05-31 22:57:52,599 - etl_pipeline - INFO - Cargando a destino... dim_tipo_servicio
2025-05-31 22:57:52,606 - etl_pipeline - INFO - Carga exitosa. Total registros: 4
2025-05-31 22:57:52,606 - etl_pipeline - INFO - ETL completado. Filas cargadas: 4 en dim_tipo_servicio
2025-05-31 22:57:52,610 - etl_pipeline - INFO - SUCCESS DIM_TIPO_SERVICIO
2025-05-31 22:57:52,611 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 22:57:52,611 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 22:57:52,611 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 22:57:52,611 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 22:57:52,612 - etl_pipeline - INFO -   - DIM_ESTADO_SERVICIO: ÉXITO
2025-05-31 22:57:52,612 - etl_pipeline - INFO -   - DIM_TIPO_SERVICIO: ÉXITO
2025-05-31 22:57:52,612 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 23:00:36,749 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 23:00:37,584 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 23:00:37,695 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 23:00:37,756 - etl_pipeline - INFO - Staging stg_dim_cliente completado (27 filas)
2025-05-31 23:00:37,757 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 23:00:37,759 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 23:00:37,759 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 23:00:37,775 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 23:00:37,775 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 23:00:37,779 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 23:00:37,843 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 23:00:37,887 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 23:00:37,889 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 23:00:37,949 - etl_pipeline - INFO - Staging stg_dim_mensajero completado (50 filas)
2025-05-31 23:00:37,950 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 23:00:37,952 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 23:00:37,952 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 23:00:37,977 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 23:00:37,978 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 23:00:37,979 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 23:00:37,982 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 23:00:38,034 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 23:00:38,220 - etl_pipeline - INFO - Staging stg_dim_novedad completado (2 filas)
2025-05-31 23:00:38,221 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 23:00:38,223 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 23:00:38,223 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 23:00:38,232 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 23:00:38,232 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 23:00:38,237 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 23:00:38,242 - etl_pipeline - INFO - Extrayendo datos... dim_estado_servicio
2025-05-31 23:00:38,298 - etl_pipeline - INFO - Cargando a staging ... dim_estado_servicio
2025-05-31 23:00:38,353 - etl_pipeline - INFO - Staging stg_dim_estado_servicio completado (6 filas)
2025-05-31 23:00:38,353 - etl_pipeline - INFO - Transformando... dim_estado_servicio
2025-05-31 23:00:38,355 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 23:00:38,355 - etl_pipeline - INFO - Cargando a destino... dim_estado_servicio
2025-05-31 23:00:38,364 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 23:00:38,365 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_estado_servicio
2025-05-31 23:00:38,368 - etl_pipeline - INFO - SUCCESS DIM_ESTADO_SERVICIO
2025-05-31 23:00:38,372 - etl_pipeline - INFO - Extrayendo datos... dim_tipo_servicio
2025-05-31 23:00:38,427 - etl_pipeline - INFO - Cargando a staging ... dim_tipo_servicio
2025-05-31 23:00:38,486 - etl_pipeline - INFO - Staging stg_dim_tipo_servicio completado (4 filas)
2025-05-31 23:00:38,487 - etl_pipeline - INFO - Transformando... dim_tipo_servicio
2025-05-31 23:00:38,488 - etl_pipeline - INFO - Transformación completada (4 filas)
2025-05-31 23:00:38,489 - etl_pipeline - INFO - Cargando a destino... dim_tipo_servicio
2025-05-31 23:00:38,498 - etl_pipeline - INFO - Carga exitosa. Total registros: 4
2025-05-31 23:00:38,499 - etl_pipeline - INFO - ETL completado. Filas cargadas: 4 en dim_tipo_servicio
2025-05-31 23:00:38,503 - etl_pipeline - INFO - SUCCESS DIM_TIPO_SERVICIO
2025-05-31 23:00:38,503 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 23:00:38,504 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 23:00:38,504 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 23:00:38,504 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 23:00:38,504 - etl_pipeline - INFO -   - DIM_ESTADO_SERVICIO: ÉXITO
2025-05-31 23:00:38,505 - etl_pipeline - INFO -   - DIM_TIPO_SERVICIO: ÉXITO
2025-05-31 23:00:38,505 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 23:02:23,902 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 23:02:24,758 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 23:02:24,869 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 23:02:24,933 - etl_pipeline - INFO - Staging stg_dim_cliente completado (27 filas)
2025-05-31 23:02:24,934 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 23:02:24,936 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 23:02:24,936 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 23:02:24,953 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 23:02:24,953 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 23:02:24,959 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 23:02:24,962 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 23:02:25,019 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 23:02:25,021 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 23:02:25,086 - etl_pipeline - INFO - Staging stg_dim_mensajero completado (50 filas)
2025-05-31 23:02:25,086 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 23:02:25,088 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 23:02:25,088 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 23:02:25,103 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 23:02:25,103 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 23:02:25,107 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 23:02:25,136 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 23:02:25,189 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 23:02:25,240 - etl_pipeline - INFO - Staging stg_dim_novedad completado (2 filas)
2025-05-31 23:02:25,240 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 23:02:25,242 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 23:02:25,242 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 23:02:25,264 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 23:02:25,265 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 23:02:25,266 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 23:02:25,270 - etl_pipeline - INFO - Extrayendo datos... dim_estado_servicio
2025-05-31 23:02:25,322 - etl_pipeline - INFO - Cargando a staging ... dim_estado_servicio
2025-05-31 23:02:25,367 - etl_pipeline - INFO - Staging stg_dim_estado_servicio completado (6 filas)
2025-05-31 23:02:25,368 - etl_pipeline - INFO - Transformando... dim_estado_servicio
2025-05-31 23:02:25,369 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 23:02:25,369 - etl_pipeline - INFO - Cargando a destino... dim_estado_servicio
2025-05-31 23:02:25,376 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 23:02:25,376 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_estado_servicio
2025-05-31 23:02:25,380 - etl_pipeline - INFO - SUCCESS DIM_ESTADO_SERVICIO
2025-05-31 23:02:25,383 - etl_pipeline - INFO - Extrayendo datos... dim_tipo_servicio
2025-05-31 23:02:25,431 - etl_pipeline - INFO - Cargando a staging ... dim_tipo_servicio
2025-05-31 23:02:25,484 - etl_pipeline - INFO - Staging stg_dim_tipo_servicio completado (4 filas)
2025-05-31 23:02:25,484 - etl_pipeline - INFO - Transformando... dim_tipo_servicio
2025-05-31 23:02:25,485 - etl_pipeline - INFO - Transformación completada (4 filas)
2025-05-31 23:02:25,486 - etl_pipeline - INFO - Cargando a destino... dim_tipo_servicio
2025-05-31 23:02:25,494 - etl_pipeline - INFO - Carga exitosa. Total registros: 4
2025-05-31 23:02:25,495 - etl_pipeline - INFO - ETL completado. Filas cargadas: 4 en dim_tipo_servicio
2025-05-31 23:02:25,497 - etl_pipeline - INFO - SUCCESS DIM_TIPO_SERVICIO
2025-05-31 23:02:25,498 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 23:02:25,498 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 23:02:25,498 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 23:02:25,498 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 23:02:25,498 - etl_pipeline - INFO -   - DIM_ESTADO_SERVICIO: ÉXITO
2025-05-31 23:02:25,498 - etl_pipeline - INFO -   - DIM_TIPO_SERVICIO: ÉXITO
2025-05-31 23:02:25,499 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 23:04:36,623 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 23:04:37,420 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 23:04:37,531 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 23:04:37,596 - etl_pipeline - INFO - Staging stg_dim_cliente completado (27 filas)
2025-05-31 23:04:37,596 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 23:04:37,598 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 23:04:37,598 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 23:04:37,617 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 23:04:37,617 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 23:04:37,621 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 23:04:37,626 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 23:04:37,683 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 23:04:37,685 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 23:04:37,752 - etl_pipeline - INFO - Staging stg_dim_mensajero completado (50 filas)
2025-05-31 23:04:37,753 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 23:04:37,755 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 23:04:37,755 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 23:04:37,769 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 23:04:37,769 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 23:04:37,773 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 23:04:37,779 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 23:04:37,831 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 23:04:37,880 - etl_pipeline - INFO - Staging stg_dim_novedad completado (2 filas)
2025-05-31 23:04:37,880 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 23:04:37,881 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 23:04:37,882 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 23:04:37,900 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 23:04:37,900 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 23:04:37,901 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 23:04:37,920 - etl_pipeline - INFO - Extrayendo datos... dim_estado_servicio
2025-05-31 23:04:37,972 - etl_pipeline - INFO - Cargando a staging ... dim_estado_servicio
2025-05-31 23:04:38,032 - etl_pipeline - INFO - Staging stg_dim_estado_servicio completado (6 filas)
2025-05-31 23:04:38,032 - etl_pipeline - INFO - Transformando... dim_estado_servicio
2025-05-31 23:04:38,035 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 23:04:38,035 - etl_pipeline - INFO - Cargando a destino... dim_estado_servicio
2025-05-31 23:04:38,065 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 23:04:38,065 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_estado_servicio
2025-05-31 23:04:38,067 - etl_pipeline - INFO - SUCCESS DIM_ESTADO_SERVICIO
2025-05-31 23:04:38,072 - etl_pipeline - INFO - Extrayendo datos... dim_tipo_servicio
2025-05-31 23:04:38,127 - etl_pipeline - INFO - Cargando a staging ... dim_tipo_servicio
2025-05-31 23:04:38,186 - etl_pipeline - INFO - Staging stg_dim_tipo_servicio completado (4 filas)
2025-05-31 23:04:38,186 - etl_pipeline - INFO - Transformando... dim_tipo_servicio
2025-05-31 23:04:38,188 - etl_pipeline - INFO - Transformación completada (4 filas)
2025-05-31 23:04:38,188 - etl_pipeline - INFO - Cargando a destino... dim_tipo_servicio
2025-05-31 23:04:38,199 - etl_pipeline - INFO - Carga exitosa. Total registros: 4
2025-05-31 23:04:38,199 - etl_pipeline - INFO - ETL completado. Filas cargadas: 4 en dim_tipo_servicio
2025-05-31 23:04:38,203 - etl_pipeline - INFO - SUCCESS DIM_TIPO_SERVICIO
2025-05-31 23:04:38,203 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 23:04:38,204 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 23:04:38,204 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 23:04:38,204 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 23:04:38,204 - etl_pipeline - INFO -   - DIM_ESTADO_SERVICIO: ÉXITO
2025-05-31 23:04:38,204 - etl_pipeline - INFO -   - DIM_TIPO_SERVICIO: ÉXITO
2025-05-31 23:04:38,204 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 23:05:44,662 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 23:05:45,504 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 23:05:45,745 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 23:05:45,815 - etl_pipeline - INFO - Staging stg_dim_cliente completado (27 filas)
2025-05-31 23:05:45,815 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 23:05:45,817 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 23:05:45,818 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 23:05:45,835 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 23:05:45,835 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 23:05:45,840 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 23:05:45,843 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 23:05:46,016 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 23:05:46,019 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 23:05:46,092 - etl_pipeline - INFO - Staging stg_dim_mensajero completado (50 filas)
2025-05-31 23:05:46,092 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 23:05:46,095 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 23:05:46,095 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 23:05:46,108 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 23:05:46,108 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 23:05:46,113 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 23:05:46,116 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 23:05:46,277 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 23:05:46,331 - etl_pipeline - INFO - Staging stg_dim_novedad completado (2 filas)
2025-05-31 23:05:46,332 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 23:05:46,333 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 23:05:46,334 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 23:05:46,341 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 23:05:46,342 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 23:05:46,344 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 23:05:46,347 - etl_pipeline - INFO - Extrayendo datos... dim_estado_servicio
2025-05-31 23:05:46,399 - etl_pipeline - INFO - Cargando a staging ... dim_estado_servicio
2025-05-31 23:05:46,452 - etl_pipeline - INFO - Staging stg_dim_estado_servicio completado (6 filas)
2025-05-31 23:05:46,452 - etl_pipeline - INFO - Transformando... dim_estado_servicio
2025-05-31 23:05:46,454 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 23:05:46,454 - etl_pipeline - INFO - Cargando a destino... dim_estado_servicio
2025-05-31 23:05:46,464 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 23:05:46,464 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_estado_servicio
2025-05-31 23:05:46,468 - etl_pipeline - INFO - SUCCESS DIM_ESTADO_SERVICIO
2025-05-31 23:05:46,498 - etl_pipeline - INFO - Extrayendo datos... dim_tipo_servicio
2025-05-31 23:05:46,548 - etl_pipeline - INFO - Cargando a staging ... dim_tipo_servicio
2025-05-31 23:05:46,604 - etl_pipeline - INFO - Staging stg_dim_tipo_servicio completado (4 filas)
2025-05-31 23:05:46,604 - etl_pipeline - INFO - Transformando... dim_tipo_servicio
2025-05-31 23:05:46,606 - etl_pipeline - INFO - Transformación completada (4 filas)
2025-05-31 23:05:46,606 - etl_pipeline - INFO - Cargando a destino... dim_tipo_servicio
2025-05-31 23:05:46,617 - etl_pipeline - ERROR - Error en carga: (psycopg2.errors.UndefinedColumn) no existe la columna «tipo_servicio_id» en la relación «dim_tipo_servicio»
LINE 1: INSERT INTO dim_tipo_servicio (tipo_servicio_key, tipo_servi...
                                                          ^

[SQL: INSERT INTO dim_tipo_servicio (tipo_servicio_key, tipo_servicio_id, nombre, descripcion) VALUES (%(tipo_servicio_key__0)s, %(tipo_servicio_id__0)s, %(nombre__0)s, %(descripcion__0)s), (%(tipo_servicio_key__1)s, %(tipo_servicio_id__1)s, %(nombre__1)s, %(descripcion__1)s), (%(tipo_servicio_key__2)s, %(tipo_servicio_id__2)s, %(nombre__2)s, %(descripcion__2)s), (%(tipo_servicio_key__3)s, %(tipo_servicio_id__3)s, %(nombre__3)s, %(descripcion__3)s)]
[parameters: {'tipo_servicio_id__0': 1, 'descripcion__0': 'Administrativo', 'tipo_servicio_key__0': 1, 'nombre__0': 'ADMINISTRATIVO', 'tipo_servicio_id__1': 2, 'descripcion__1': 'Comercial', 'tipo_servicio_key__1': 2, 'nombre__1': 'COMERCIAL', 'tipo_servicio_id__2': 3, 'descripcion__2': 'Clínico', 'tipo_servicio_key__2': 3, 'nombre__2': 'CLÍNICO', 'tipo_servicio_id__3': 4, 'descripcion__3': 'Urgencia Vital', 'tipo_servicio_key__3': 4, 'nombre__3': 'URGENCIA VITAL'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2114, in _exec_insertmany_context
    dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~^
        cursor,
        ^^^^^^^
    ...<2 lines>...
        context,
        ^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: no existe la columna «tipo_servicio_id» en la relación «dim_tipo_servicio»
LINE 1: INSERT INTO dim_tipo_servicio (tipo_servicio_key, tipo_servi...
                                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\load\load_dim_tipo_servicio.py", line 27, in run_load
    df.to_sql(
    ~~~~~~~~~^
        'dim_tipo_servicio',
        ^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        chunksize=1000
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\core\generic.py", line 3087, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 2018, in to_sql
    total_inserted = sql_engine.insert_records(
        table=table,
    ...<7 lines>...
        **engine_kwargs,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1567, in insert_records
    raise err
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1558, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1119, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\pandas\io\sql.py", line 1010, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1840, in _execute_context
    return self._exec_insertmany_context(dialect, context)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2122, in _exec_insertmany_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e,
        ^^
    ...<4 lines>...
        is_sub_exec=True,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2114, in _exec_insertmany_context
    dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~^
        cursor,
        ^^^^^^^
    ...<2 lines>...
        context,
        ^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) no existe la columna «tipo_servicio_id» en la relación «dim_tipo_servicio»
LINE 1: INSERT INTO dim_tipo_servicio (tipo_servicio_key, tipo_servi...
                                                          ^

[SQL: INSERT INTO dim_tipo_servicio (tipo_servicio_key, tipo_servicio_id, nombre, descripcion) VALUES (%(tipo_servicio_key__0)s, %(tipo_servicio_id__0)s, %(nombre__0)s, %(descripcion__0)s), (%(tipo_servicio_key__1)s, %(tipo_servicio_id__1)s, %(nombre__1)s, %(descripcion__1)s), (%(tipo_servicio_key__2)s, %(tipo_servicio_id__2)s, %(nombre__2)s, %(descripcion__2)s), (%(tipo_servicio_key__3)s, %(tipo_servicio_id__3)s, %(nombre__3)s, %(descripcion__3)s)]
[parameters: {'tipo_servicio_id__0': 1, 'descripcion__0': 'Administrativo', 'tipo_servicio_key__0': 1, 'nombre__0': 'ADMINISTRATIVO', 'tipo_servicio_id__1': 2, 'descripcion__1': 'Comercial', 'tipo_servicio_key__1': 2, 'nombre__1': 'COMERCIAL', 'tipo_servicio_id__2': 3, 'descripcion__2': 'Clínico', 'tipo_servicio_key__2': 3, 'nombre__2': 'CLÍNICO', 'tipo_servicio_id__3': 4, 'descripcion__3': 'Urgencia Vital', 'tipo_servicio_key__3': 4, 'nombre__3': 'URGENCIA VITAL'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-31 23:05:46,627 - etl_pipeline - INFO - ERROR DIM_TIPO_SERVICIO
2025-05-31 23:05:46,627 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 23:05:46,627 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 23:05:46,628 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 23:05:46,628 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 23:05:46,628 - etl_pipeline - INFO -   - DIM_ESTADO_SERVICIO: ÉXITO
2025-05-31 23:05:46,628 - etl_pipeline - INFO -   - DIM_TIPO_SERVICIO: FALLÓ
2025-05-31 23:05:46,628 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 23:05:56,734 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 23:05:57,470 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 23:05:57,576 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 23:05:57,757 - etl_pipeline - INFO - Staging stg_dim_cliente completado (27 filas)
2025-05-31 23:05:57,758 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 23:05:57,759 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 23:05:57,760 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 23:05:57,777 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 23:05:57,778 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 23:05:57,782 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 23:05:57,785 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 23:05:57,848 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 23:05:57,850 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 23:05:58,044 - etl_pipeline - INFO - Staging stg_dim_mensajero completado (50 filas)
2025-05-31 23:05:58,044 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 23:05:58,047 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 23:05:58,047 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 23:05:58,065 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 23:05:58,066 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 23:05:58,070 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 23:05:58,075 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 23:05:58,123 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 23:05:58,172 - etl_pipeline - INFO - Staging stg_dim_novedad completado (2 filas)
2025-05-31 23:05:58,173 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 23:05:58,174 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 23:05:58,174 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 23:05:58,183 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 23:05:58,183 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 23:05:58,186 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 23:05:58,189 - etl_pipeline - INFO - Extrayendo datos... dim_estado_servicio
2025-05-31 23:05:58,240 - etl_pipeline - INFO - Cargando a staging ... dim_estado_servicio
2025-05-31 23:05:58,291 - etl_pipeline - INFO - Staging stg_dim_estado_servicio completado (6 filas)
2025-05-31 23:05:58,292 - etl_pipeline - INFO - Transformando... dim_estado_servicio
2025-05-31 23:05:58,293 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 23:05:58,294 - etl_pipeline - INFO - Cargando a destino... dim_estado_servicio
2025-05-31 23:05:58,304 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 23:05:58,304 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_estado_servicio
2025-05-31 23:05:58,308 - etl_pipeline - INFO - SUCCESS DIM_ESTADO_SERVICIO
2025-05-31 23:05:58,312 - etl_pipeline - INFO - Extrayendo datos... dim_tipo_servicio
2025-05-31 23:05:58,488 - etl_pipeline - INFO - Cargando a staging ... dim_tipo_servicio
2025-05-31 23:05:58,550 - etl_pipeline - INFO - Staging stg_dim_tipo_servicio completado (4 filas)
2025-05-31 23:05:58,550 - etl_pipeline - INFO - Transformando... dim_tipo_servicio
2025-05-31 23:05:58,553 - etl_pipeline - INFO - Transformación completada (4 filas)
2025-05-31 23:05:58,553 - etl_pipeline - INFO - Cargando a destino... dim_tipo_servicio
2025-05-31 23:05:58,575 - etl_pipeline - INFO - Carga exitosa. Total registros: 4
2025-05-31 23:05:58,575 - etl_pipeline - INFO - ETL completado. Filas cargadas: 4 en dim_tipo_servicio
2025-05-31 23:05:58,576 - etl_pipeline - INFO - SUCCESS DIM_TIPO_SERVICIO
2025-05-31 23:05:58,577 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 23:05:58,577 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 23:05:58,577 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 23:05:58,577 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 23:05:58,578 - etl_pipeline - INFO -   - DIM_ESTADO_SERVICIO: ÉXITO
2025-05-31 23:05:58,578 - etl_pipeline - INFO -   - DIM_TIPO_SERVICIO: ÉXITO
2025-05-31 23:05:58,578 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
2025-05-31 23:48:39,865 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 23:48:40,446 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 23:48:40,651 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 23:48:40,687 - etl_pipeline - INFO - Staging stg_dim_cliente completado (27 filas)
2025-05-31 23:48:40,687 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 23:48:40,688 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 23:48:40,689 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 23:48:40,701 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 23:48:40,701 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 23:48:40,703 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 23:48:40,706 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 23:48:40,740 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 23:48:40,742 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 23:48:40,778 - etl_pipeline - INFO - Staging stg_dim_mensajero completado (50 filas)
2025-05-31 23:48:40,778 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 23:48:40,780 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 23:48:40,780 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 23:48:40,790 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 23:48:40,791 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 23:48:40,793 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 23:48:40,796 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 23:48:40,832 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 23:48:40,987 - etl_pipeline - INFO - Staging stg_dim_novedad completado (2 filas)
2025-05-31 23:48:40,987 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 23:48:40,988 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 23:48:40,988 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 23:48:40,995 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 23:48:40,996 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 23:48:40,998 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 23:48:41,000 - etl_pipeline - INFO - Extrayendo datos... dim_estado_servicio
2025-05-31 23:48:41,030 - etl_pipeline - INFO - Cargando a staging ... dim_estado_servicio
2025-05-31 23:48:41,062 - etl_pipeline - INFO - Staging stg_dim_estado_servicio completado (6 filas)
2025-05-31 23:48:41,063 - etl_pipeline - INFO - Transformando... dim_estado_servicio
2025-05-31 23:48:41,064 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 23:48:41,064 - etl_pipeline - INFO - Cargando a destino... dim_estado_servicio
2025-05-31 23:48:41,069 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 23:48:41,069 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_estado_servicio
2025-05-31 23:48:41,072 - etl_pipeline - INFO - SUCCESS DIM_ESTADO_SERVICIO
2025-05-31 23:48:41,074 - etl_pipeline - INFO - Extrayendo datos... dim_tipo_servicio
2025-05-31 23:48:41,109 - etl_pipeline - INFO - Cargando a staging ... dim_tipo_servicio
2025-05-31 23:48:41,150 - etl_pipeline - INFO - Staging stg_dim_tipo_servicio completado (4 filas)
2025-05-31 23:48:41,151 - etl_pipeline - INFO - Transformando... dim_tipo_servicio
2025-05-31 23:48:41,152 - etl_pipeline - INFO - Transformación completada (4 filas)
2025-05-31 23:48:41,152 - etl_pipeline - INFO - Cargando a destino... dim_tipo_servicio
2025-05-31 23:48:41,160 - etl_pipeline - INFO - Carga exitosa. Total registros: 4
2025-05-31 23:48:41,160 - etl_pipeline - INFO - ETL completado. Filas cargadas: 4 en dim_tipo_servicio
2025-05-31 23:48:41,162 - etl_pipeline - INFO - SUCCESS DIM_TIPO_SERVICIO
2025-05-31 23:48:41,183 - etl_pipeline - INFO - Extrayendo datos... dim_sede
2025-05-31 23:48:41,216 - etl_pipeline - INFO - Cargando a staging ... dim_sede
2025-05-31 23:48:41,254 - etl_pipeline - INFO - Staging stg_dim_sede completado (52 filas)
2025-05-31 23:48:41,255 - etl_pipeline - INFO - Transformando... dim_sede
2025-05-31 23:48:41,256 - etl_pipeline - INFO - Transformación completada (52 filas)
2025-05-31 23:48:41,257 - etl_pipeline - INFO - Cargando a destino... dim_sede
2025-05-31 23:48:41,258 - etl_pipeline - ERROR - Error en carga: (psycopg2.errors.SyntaxError) error de sintaxis en o cerca de «created_at»
LINE 12:             created_at        TIMESTAMP DEFAULT CURRENT_TIME...
                     ^

[SQL: 
        CREATE TABLE IF NOT EXISTS dim_sede (
            sede_key          INTEGER PRIMARY KEY,
            sede_id           INTEGER NOT NULL,
            nombre            VARCHAR(120) NOT NULL,
            direccion         VARCHAR(250),
            ciudad            VARCHAR(120) NOT NULL,
            departamento      VARCHAR(120) NOT NULL,
            cliente_id        INTEGER NOT NULL,                 
            nit_cliente       VARCHAR(50) NOT NULL,
            nombre_cliente    VARCHAR(120) NOT NULL
            created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uk_sede_id UNIQUE (sede_id)
        )
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.SyntaxError: error de sintaxis en o cerca de «created_at»
LINE 12:             created_at        TIMESTAMP DEFAULT CURRENT_TIME...
                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\src\load\load_dim_sede.py", line 11, in run_load
    session.execute(text("""
    ~~~~~~~~~~~~~~~^^^^^^^^^
    CREATE TABLE IF NOT EXISTS dim_sede (
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
    """))
    ^^^^^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2260, in _execute_internal
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Camilo\Dev\maestria-proyecto-mensajeria-etl\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) error de sintaxis en o cerca de «created_at»
LINE 12:             created_at        TIMESTAMP DEFAULT CURRENT_TIME...
                     ^

[SQL: 
        CREATE TABLE IF NOT EXISTS dim_sede (
            sede_key          INTEGER PRIMARY KEY,
            sede_id           INTEGER NOT NULL,
            nombre            VARCHAR(120) NOT NULL,
            direccion         VARCHAR(250),
            ciudad            VARCHAR(120) NOT NULL,
            departamento      VARCHAR(120) NOT NULL,
            cliente_id        INTEGER NOT NULL,                 
            nit_cliente       VARCHAR(50) NOT NULL,
            nombre_cliente    VARCHAR(120) NOT NULL
            created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uk_sede_id UNIQUE (sede_id)
        )
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-31 23:48:41,262 - etl_pipeline - INFO - ERROR DIM_SEDE
2025-05-31 23:48:41,263 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 23:48:41,263 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 23:48:41,263 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 23:48:41,263 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 23:48:41,263 - etl_pipeline - INFO -   - DIM_ESTADO_SERVICIO: ÉXITO
2025-05-31 23:48:41,263 - etl_pipeline - INFO -   - DIM_TIPO_SERVICIO: ÉXITO
2025-05-31 23:48:41,263 - etl_pipeline - INFO -   - DIM_SEDE       : FALLÓ
2025-05-31 23:48:41,263 - etl_pipeline - ERROR - Algunos pipelines fallaron. Ver logs.
2025-05-31 23:49:14,466 - etl_pipeline - INFO - Iniciando ETL Master
2025-05-31 23:49:14,931 - etl_pipeline - INFO - Extrayendo datos... dim_cliente
2025-05-31 23:49:15,008 - etl_pipeline - INFO - Cargando a staging ... dim_cliente
2025-05-31 23:49:15,053 - etl_pipeline - INFO - Staging stg_dim_cliente completado (27 filas)
2025-05-31 23:49:15,053 - etl_pipeline - INFO - Transformando... dim_cliente
2025-05-31 23:49:15,054 - etl_pipeline - INFO - Transformación completada (27 filas)
2025-05-31 23:49:15,054 - etl_pipeline - INFO - Cargando a destino... dim_cliente
2025-05-31 23:49:15,066 - etl_pipeline - INFO - Carga exitosa. Total registros: 27
2025-05-31 23:49:15,066 - etl_pipeline - INFO - ETL completado. Filas cargadas: 27 en dim_cliente
2025-05-31 23:49:15,068 - etl_pipeline - INFO - SUCCESS DIM_CLIENTE
2025-05-31 23:49:15,069 - etl_pipeline - INFO - Extrayendo datos... dim_mensajero
2025-05-31 23:49:15,102 - etl_pipeline - INFO - Extraídos 50 registros de mensajeros
2025-05-31 23:49:15,104 - etl_pipeline - INFO - Cargando a staging ... dim_mensajero
2025-05-31 23:49:15,141 - etl_pipeline - INFO - Staging stg_dim_mensajero completado (50 filas)
2025-05-31 23:49:15,142 - etl_pipeline - INFO - Transformando... dim_mensajero
2025-05-31 23:49:15,143 - etl_pipeline - INFO - Transformación completada (50 filas)
2025-05-31 23:49:15,143 - etl_pipeline - INFO - Cargando a destino... dim_mensajero
2025-05-31 23:49:15,153 - etl_pipeline - INFO - Carga exitosa. Total registros: 50
2025-05-31 23:49:15,153 - etl_pipeline - INFO - ETL completado. Filas cargadas: 50 en dim_mensajero
2025-05-31 23:49:15,156 - etl_pipeline - INFO - SUCCESS DIM_MENSAJERO
2025-05-31 23:49:15,158 - etl_pipeline - INFO - Extrayendo datos... dim_novedad
2025-05-31 23:49:15,222 - etl_pipeline - INFO - Cargando a staging ... dim_novedad
2025-05-31 23:49:15,265 - etl_pipeline - INFO - Staging stg_dim_novedad completado (2 filas)
2025-05-31 23:49:15,265 - etl_pipeline - INFO - Transformando... dim_novedad
2025-05-31 23:49:15,266 - etl_pipeline - INFO - Transformación completada (2 filas)
2025-05-31 23:49:15,266 - etl_pipeline - INFO - Cargando a destino... dim_novedad
2025-05-31 23:49:15,271 - etl_pipeline - INFO - Carga exitosa. Total registros: 2
2025-05-31 23:49:15,271 - etl_pipeline - INFO - ETL completado. Filas cargadas: 2 en dim_novedad
2025-05-31 23:49:15,273 - etl_pipeline - INFO - SUCCESS DIM_NOVEDAD
2025-05-31 23:49:15,274 - etl_pipeline - INFO - Extrayendo datos... dim_estado_servicio
2025-05-31 23:49:15,306 - etl_pipeline - INFO - Cargando a staging ... dim_estado_servicio
2025-05-31 23:49:15,337 - etl_pipeline - INFO - Staging stg_dim_estado_servicio completado (6 filas)
2025-05-31 23:49:15,338 - etl_pipeline - INFO - Transformando... dim_estado_servicio
2025-05-31 23:49:15,339 - etl_pipeline - INFO - Transformación completada (6 filas)
2025-05-31 23:49:15,339 - etl_pipeline - INFO - Cargando a destino... dim_estado_servicio
2025-05-31 23:49:15,344 - etl_pipeline - INFO - Carga exitosa. Total registros: 6
2025-05-31 23:49:15,344 - etl_pipeline - INFO - ETL completado. Filas cargadas: 6 en dim_estado_servicio
2025-05-31 23:49:15,346 - etl_pipeline - INFO - SUCCESS DIM_ESTADO_SERVICIO
2025-05-31 23:49:15,347 - etl_pipeline - INFO - Extrayendo datos... dim_tipo_servicio
2025-05-31 23:49:15,381 - etl_pipeline - INFO - Cargando a staging ... dim_tipo_servicio
2025-05-31 23:49:15,417 - etl_pipeline - INFO - Staging stg_dim_tipo_servicio completado (4 filas)
2025-05-31 23:49:15,418 - etl_pipeline - INFO - Transformando... dim_tipo_servicio
2025-05-31 23:49:15,419 - etl_pipeline - INFO - Transformación completada (4 filas)
2025-05-31 23:49:15,420 - etl_pipeline - INFO - Cargando a destino... dim_tipo_servicio
2025-05-31 23:49:15,426 - etl_pipeline - INFO - Carga exitosa. Total registros: 4
2025-05-31 23:49:15,427 - etl_pipeline - INFO - ETL completado. Filas cargadas: 4 en dim_tipo_servicio
2025-05-31 23:49:15,428 - etl_pipeline - INFO - SUCCESS DIM_TIPO_SERVICIO
2025-05-31 23:49:15,441 - etl_pipeline - INFO - Extrayendo datos... dim_sede
2025-05-31 23:49:15,478 - etl_pipeline - INFO - Cargando a staging ... dim_sede
2025-05-31 23:49:15,516 - etl_pipeline - INFO - Staging stg_dim_sede completado (52 filas)
2025-05-31 23:49:15,517 - etl_pipeline - INFO - Transformando... dim_sede
2025-05-31 23:49:15,518 - etl_pipeline - INFO - Transformación completada (52 filas)
2025-05-31 23:49:15,518 - etl_pipeline - INFO - Cargando a destino... dim_sede
2025-05-31 23:49:15,530 - etl_pipeline - INFO - Carga exitosa. Total registros: 52
2025-05-31 23:49:15,530 - etl_pipeline - INFO - ETL completado. Filas cargadas: 52 en dim_sede
2025-05-31 23:49:15,531 - etl_pipeline - INFO - SUCCESS DIM_SEDE
2025-05-31 23:49:15,531 - etl_pipeline - INFO - Resumen de ejecución:
2025-05-31 23:49:15,531 - etl_pipeline - INFO -   - DIM_CLIENTE    : ÉXITO
2025-05-31 23:49:15,531 - etl_pipeline - INFO -   - DIM_MENSAJERO  : ÉXITO
2025-05-31 23:49:15,531 - etl_pipeline - INFO -   - DIM_NOVEDAD    : ÉXITO
2025-05-31 23:49:15,531 - etl_pipeline - INFO -   - DIM_ESTADO_SERVICIO: ÉXITO
2025-05-31 23:49:15,531 - etl_pipeline - INFO -   - DIM_TIPO_SERVICIO: ÉXITO
2025-05-31 23:49:15,531 - etl_pipeline - INFO -   - DIM_SEDE       : ÉXITO
2025-05-31 23:49:15,531 - etl_pipeline - INFO - ¡Todos los pipelines completados con éxito!
